-- Tabela Postagem
CREATE TABLE Postagem (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL,
    conteudo TEXT NOT NULL,
    imagem VARCHAR(255),
    qntd_estrelas INT DEFAULT 0,
    autor VARCHAR(100) NOT NULL,
    tags VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabela Comentários
CREATE TABLE Comentarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_postagem INT,
    conteudo TEXT NOT NULL,
    qntd_estrelas INT DEFAULT 0,
    autor VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_postagem) REFERENCES Postagem(id) ON DELETE CASCADE
);
